### ISSUE TITLE
RepositoryItemWriter not inserting on execution

### ISSUE THREAD

**Issue by uesleilima** [codecentric/spring-boot-starter-batch-web#48]
Hi, when using this library every time I execute a job using a RepositoryItemWriter it does not generate the inserts in database. 
I'm using jpa, hibernate with oracle. On enabling "spring.jpa.show-sql=true" property I can see the are no insert being executed by hibernate. 
After just removing the spring-boot-starter-batch-web 1.4.0.RELEASE dependency from my pom, and re-executing the Job, the inserts are there.
Is this any configuration issue? How can I fix it?

**Comment by Katona** [comment]
I have the exact same problem, is there any news on this? Does anybody know what causes the problem?

**Comment by Katona** [comment]
In the meantime we managed to solve it. The problem seems to be that spring-boot-starter-batch-web defines a `DataSourceTransactionManager` which doesn't work properly with JPA. We managed to solve it by defining a `JpaTransactionManager` in our configuration which implements the `BatchConfigurer` interface.

**Comment by dickerpulli** [comment]
This is how it should be done: https://github.com/codecentric/spring-boot-starter-batch-web/issues/48#issuecomment-351400224
